import {Deck} from "../../app/shared/models/deck";
import {
  BlightedTreant,
  ForestFire,
  WoodlandsElven,
  TreetopSociety,
  Sawmill,
  Scout,
  SpiritWolf,
  GreenLair,
  LogManufacturingPlant,
  WoodlandsHuntress,
  PrimalWrath,
  RootGolem,
  OpenWilderness,
  OvergrownTemple,
  BearBrute,
  TribeLeader,
  DawnDrake,
  Wetlands,
  StormValley,
  VerdantSanctuary,
  LostParadise,
  Terraform,
  SpiritDeer,
  SpiritDragon,
  WoodlandsScavenger,
  Terraduct,
  WoodlandsExile,
  FleshToSoil,
  ShadowSurge,
  GardenOfHope,
  ElderwoodProphet,
  Craftsmanship,
  ElderwoodDryad,
  ThicketSpawn,
  SpiritTree,
  JungleRebornRitual,
  JungleWyrm,
  WoodlandsApexPredator,
  SummonedSaplings,
  ANewBeginning,
  ElderwoodTreant, ElderwoodStag, SpiritCrow
} from "../../app/shared/card";
import {Injectable} from "@angular/core";

@Injectable()
export class TestDeck2 {

  deck: Deck = {
    cards: [
      new Sawmill(),
      new LogManufacturingPlant(),
      new TreetopSociety(),
      new Scout(),
      new SpiritWolf(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new OpenWilderness(),
      new TribeLeader(),
      new Wetlands(),
      new StormValley(),
      new LostParadise(),
      new SpiritDeer(),
      new SpiritDragon(),
      new WoodlandsScavenger(),
      new WoodlandsExile(),
      new GardenOfHope(),
      new ElderwoodProphet(),
      new Craftsmanship(),
      new Craftsmanship(),
      new SpiritTree(),
      new JungleRebornRitual(),
      new Sawmill(),
      new LogManufacturingPlant(),
      new TreetopSociety(),
      new Scout(),
      new SpiritWolf(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new OpenWilderness(),
      new OpenWilderness(),
      new TribeLeader(),
      new Wetlands(),
      new StormValley(),
      new LostParadise(),
      new SpiritDeer(),
      new SpiritDragon(),
      new WoodlandsScavenger(),
      new WoodlandsScavenger(),
      new WoodlandsExile(),
      new GardenOfHope(),
      new ElderwoodProphet(),
      new Craftsmanship(),
      new SpiritTree(),
      new JungleRebornRitual(),
      new SummonedSaplings(),
      new SummonedSaplings(),
      new ANewBeginning(),
      new ANewBeginning(),
      new ANewBeginning(),
      new ElderwoodTreant(),
      new ElderwoodTreant(),
      new ElderwoodDryad(),
      new ElderwoodDryad(),
      new OvergrownTemple(),
      new OvergrownTemple(),
      new DawnDrake(),
      new DawnDrake(),
      new WoodlandsApexPredator(),
      new WoodlandsApexPredator(),
      new ElderwoodStag(),
      new ElderwoodStag(),
      new SpiritCrow(),
      new SpiritCrow()
    ]
  }
}
