import {Deck} from "../../app/shared/models/deck";
import {
  BlightedTreant,
  ForestFire,
  WoodlandsElven,
  TreetopSociety,
  Sawmill,
  Scout,
  SpiritWolf,
  GreenLair,
  LogManufacturingPlant,
  WoodlandsHuntress,
  PrimalWrath,
  RootGolem,
  OpenWilderness,
  OvergrownTemple,
  BearBrute,
  TribeLeader,
  DawnDrake,
  Wetlands,
  StormValley,
  VerdantSanctuary,
  LostParadise,
  Terraform,
  SpiritDeer,
  SpiritDragon,
  WoodlandsScavenger,
  Terraduct,
  WoodlandsExile,
  FleshToSoil,
  ShadowSurge,
  GardenOfHope,
  ElderwoodProphet,
  Craftsmanship,
  ElderwoodDryad,
  ThicketSpawn, SpiritTree, JungleRebornRitual, JungleWyrm, WoodlandsApexPredator
} from "../../app/shared/card";
import {Injectable} from "@angular/core";

@Injectable()
export class TestDeck {

  deck: Deck = {
    cards: [
      new Sawmill(),
      new LogManufacturingPlant(),
      new TreetopSociety(),
      new Scout(),
      new SpiritWolf(),
      new BlightedTreant(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new RootGolem(),
      new OpenWilderness(),
      new OvergrownTemple(),
      new BearBrute(),
      new TribeLeader(),
      new DawnDrake(),
      new Wetlands(),
      new StormValley(),
      new VerdantSanctuary(),
      new LostParadise(),
      new Terraform(),
      new SpiritDeer(),
      new SpiritDragon(),
      new WoodlandsScavenger(),
      new Terraduct(),
      new WoodlandsExile(),
      new FleshToSoil(),
      new ShadowSurge(),
      new GardenOfHope(),
      new ElderwoodProphet(),
      new Craftsmanship(),
      new ElderwoodDryad(),
      new ThicketSpawn(),
      new SpiritTree(),
      new JungleRebornRitual(),
      new JungleWyrm(),
      new WoodlandsApexPredator()
    ]
  }
}
