import {Deck} from "../../app/shared/models/deck";
import {
  BlightedTreant,
  ForestFire,
  WoodlandsElven,
  TreetopSociety,
  Sawmill,
  Scout,
  SpiritWolf,
  GreenLair,
  WoodFactory,
  WoodlandsHuntress,
  PrimalWrath,
  RootGolem,
  OpenWilderness,
  OvergrownTemple,
  BearBrute,
  TribeLeader,
  LeafDrake,
  Wetlands,
  StormValley,
  VerdantSanctuary,
  LostParadise,
  Terraform,
  SpiritDeer,
  SpiritDragon,
  WoodlandsScavenger,
  Terraduct,
  WoodlandsExile,
  FleshToSoil,
  ShadowSurge,
  GardenOfHope,
  ElderwoodProphet,
  Craftsmanship,
  WoodlandsDryad,
  ThicketDevourer, SpiritTree, JungleRebornRitual, JungleWyrm, WoodlandsApexPredator
} from "../../app/shared/card";
import {Injectable} from "@angular/core";

@Injectable()
export class TestDeck {

  deck: Deck = {
    cards: [
      new Sawmill(),
      new WoodFactory(),
      new TreetopSociety(),
      new Scout(),
      new SpiritWolf(),
      new BlightedTreant(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new RootGolem(),
      new OpenWilderness(),
      new OvergrownTemple(),
      new BearBrute(),
      new TribeLeader(),
      new Sawmill(),
      new WoodFactory(),
      new TreetopSociety(),
      new Scout(),
      new SpiritWolf(),
      new BlightedTreant(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new RootGolem(),
      new OpenWilderness(),
      new OvergrownTemple(),
      new BearBrute(),
      new TribeLeader(),
      new LeafDrake(),
      new LeafDrake(),
      new Wetlands(),
      new Wetlands(),
      new StormValley(),
      new StormValley(),
      new VerdantSanctuary(),
      new VerdantSanctuary(),
      new LostParadise(),
      new LostParadise(),
      new Terraform(),
      new Terraform(),
      new SpiritDeer(),
      new SpiritDeer(),
      new SpiritDragon(),
      new SpiritDragon(),
      new WoodlandsScavenger(),
      new WoodlandsScavenger(),
      new Terraduct(),
      new Terraduct(),
      new WoodlandsExile(),
      new WoodlandsExile(),
      new FleshToSoil(),
      new FleshToSoil(),
      new ShadowSurge(),
      new ShadowSurge(),
      new GardenOfHope(),
      new GardenOfHope(),
      new ElderwoodProphet(),
      new ElderwoodProphet(),
      new Craftsmanship(),
      new Craftsmanship(),
      new WoodlandsDryad(),
      new WoodlandsDryad(),
      new ThicketDevourer(),
      new ThicketDevourer(),
      new SpiritTree(),
      new SpiritTree(),
      new JungleRebornRitual(),
      new JungleRebornRitual(),
      new JungleWyrm(),
      new JungleWyrm(),
      new WoodlandsApexPredator(),
      new WoodlandsApexPredator()
    ]
  }
}
