import {Deck} from "../../app/shared/models/deck";
import {
  ANewBeginning,
  BearBrute,
  Bioterror,
  BlightedTreant,
  Craftsmanship,
  DawnDrake,
  ElderwoodDryad,
  ElderwoodProphet,
  ElderwoodStag,
  ElderwoodTreant,
  ForestFire,
  GardenOfHope,
  GreenLair,
  JungleRebornRitual, JungleShrine,
  JungleWyrm,
  LogManufacturingPlant,
  LostParadise,
  OpenWilderness,
  OvergrownTemple,
  PrimalWrath,
  RootGolem,
  Sawmill,
  SpiritCrows,
  SpiritDeer,
  SpiritDragon,
  SpiritTree,
  SpiritWolf,
  StormValley,
  SummonedSaplings,
  Terraduct,
  Terraform,
  ThicketSpawn, TimeShiftingJungle,
  TreetopSociety,
  TribeLeader,
  VerdantSanctuary,
  Wetlands,
  WoodlandsApexPredator,
  WoodlandsElven,
  WoodlandsExile,
  WoodlandsHuntress,
  WoodlandsScavenger,
  WoodlandsScout,
  WoodlandsWitch
} from "../../app/shared/card";
import {Injectable} from "@angular/core";

@Injectable()
export class WoodlandsDeck {

  deck: Deck = {
    cards: [
      new Sawmill(),
      new Sawmill(),
      new LogManufacturingPlant(),
      new LogManufacturingPlant(),
      new TreetopSociety(),
      new WoodlandsScout(),
      new WoodlandsScout(),
      new SpiritWolf(),
      new SpiritWolf(),
      new SpiritWolf(),
      new WoodlandsHuntress(),
      new WoodlandsElven(),
      new GreenLair(),
      new ForestFire(),
      new PrimalWrath(),
      new OpenWilderness(),
      new OpenWilderness(),
      new OpenWilderness(),
      new TribeLeader(),
      new Wetlands(),
      new LostParadise(),
      new SpiritDeer(),
      new SpiritDeer(),
      new SpiritDragon(),
      new SpiritDragon(),
      new WoodlandsScavenger(),
      new WoodlandsScavenger(),
      new WoodlandsScavenger(),
      new WoodlandsExile(),
      new WoodlandsExile(),
      new GardenOfHope(),
      new GardenOfHope(),
      new ElderwoodProphet(),
      new ElderwoodProphet(),
      new ElderwoodProphet(),
      new Craftsmanship(),
      new Craftsmanship(),
      new Craftsmanship(),
      new SpiritTree(),
      new SpiritTree(),
      new JungleRebornRitual(),
      new SummonedSaplings(),
      new SummonedSaplings(),
      new SummonedSaplings(),
      new ANewBeginning(),
      new ANewBeginning(),
      new ANewBeginning(),
      new ElderwoodTreant(),
      new ElderwoodDryad(),
      new ElderwoodDryad(),
      new ElderwoodDryad(),
      new OvergrownTemple(),
      new OvergrownTemple(),
      new DawnDrake(),
      new WoodlandsApexPredator(),
      new ElderwoodStag(),
      new ElderwoodStag(),
      new SpiritCrows(),
      new SpiritCrows(),
      new SpiritCrows(),
      new VerdantSanctuary(),
      new Terraduct(),
      new Terraform(),
      new ThicketSpawn(),
      new JungleWyrm(),
      new Bioterror(),
      new WoodlandsWitch(),
      new WoodlandsWitch(),
      new TimeShiftingJungle(),
      new TimeShiftingJungle(),
      new JungleShrine(),
      new JungleShrine()
    ]
  }
}
